#!/bin/bash

# ------------------------------------------------------
# This scripts aim to run Augeas tool (command augtool)
# to change content of specific xml file
# ------------------------------------------------------


# -------------------------------------------
# ---------------- FUNCTIONS ----------------
# -------------------------------------------
function usage() {
cat << EOF
Usage:
`basename $0` path_to_augeas_rules path_to_xml [file_with_bash_variables] [OPTIONS]
  path_to_augeas_rules       path to files with augeas rules but without loading file and setting xml lenses
                             the loading and saving are done at the end of this script
                             please, be sure to escape Augeas variables otherwise it will be expanded as bash variables
  path_to_xml                file that will be changed by the augeas processing(rules)
  file_with_bash_variables   file with variables that will be expanded to path_to_augeas_rules
 Options:
  -h Show help options.
  -Dvariable_name=value  Define variable that is used for replacement of data in xml file.
                         This variable will override a value from bash variable file if defined.
 WARNING: if you run this script against some Augeas script then be sure to escape augeas variables (defvar) by backslash
          not slashed variables will be handled as bash variables and will be expanded
EOF
}

# Parsing variables defined as script options
function parseVariables() {
  PARSED_VARIABLES=0
  while [ $# -gt 0 ] && [[ "$1" =~ ^-D([^=]+)=(.*) ]]; do
    [ "$DEBUG" = true ] || [ "$debug" = true ] && echo "parsing $1"
    VAR_NAME=`echo ${BASH_REMATCH[1]} | sed 's/\./_/g'`
    VAR_VALUE="${BASH_REMATCH[2]}"
    eval "${VAR_NAME}=${VAR_VALUE}"
    shift
    PARSED_VARIABLES=$(($PARSED_VARIABLES+1))
  done
}

# Loading file with augeas rules and running evaluation over the file
# to inject values of bash variables defined by script or script parameters
function evalAugeas() {
  [ "x$1" = "x" ] && echo "No argument of filename specified" && return
  local LINE
  # flag -r tells read not to treat backslashes as escape char
  while read -r LINE; do
    local EVALUATED_LINE=`eval "echo \"${LINE}\""`
    # comment line (btw. quoting regexp:  http://stackoverflow.com/questions/218156/bash-regex-with-quotes)
    [[ "$EVALUATED_LINE" =~ `echo "^[ ]*[#]"` ]] && continue
    # including different file
    if [[ "$EVALUATED_LINE" =~ `echo "^[ ]*\binclude\b[ ]+(.*)"` ]]; then
      local MATCH="${BASH_REMATCH[1]}"
      # possibly looking relatively from directory where this script is placed in
      [ ! -f "$MATCH" ] && MATCH="$(dirname $([ -L $0 ] && readlink -f $0 || echo $0))/${MATCH}"
      [ -f "$MATCH" ] && evalAugeas "$MATCH" || >&2 echo "Can't include '$MATCH' as not a file in ruleset '$1'"
      continue
    fi
    # printf is needed to get new lines added on \n
    printf -v TEMPLATE "${TEMPLATE}${EVALUATED_LINE}\n"
  done < "$1"
}


# -----------------------------------------------
# ---------------- SCRIPT ITSELF ----------------
# -----------------------------------------------
[ "$DEBUG" = true ] || [ "$debug" = true ] && echo "Calling: $0 $@"
# Taking off variables defined right after the script name
# variable means '-Dname=value'
parseVariables "$@"
shift $PARSED_VARIABLES

# Printing help
[[ "$*" =~ -[-]{0,1}(h|help)( |$) ]] && usage && exit
[ $# -eq 0 ] && usage && echo " -> No arguments defined" && exit
[[ "$1" =~ ^- ]] || [ "$2" = "" ] || [[ "$2" =~ ^- ]] && usage \
   && echo " -> First two arguments are obligatory to be paths to files" && exit
! [ -f "$1" ] && usage && echo " -> Can't find file '$1' that should contain augeas rules" && exit


AUGEASFILE="$1"
shift
# If we are able to touch the file in second argumetn (which is xml to transform)
# changing it to an absolute path. If not leaving it as it is as. Asterisk notation
# could be used (e.g. /abs/path/configuration/standalone*.xml)
[ -f "$1" ] && XMLFILE=`readlink -f "$1"` || XMLFILE="$1"
[[ ! "$XMLFILE" =~ ^/ ]] && echo "Please define the XML file(s) descriptor '$1' as absolute path" && exit
shift
VARIABLESFILE=
[ -f "$1" ] && VARIABLESFILE="$1" && shift

# Injecting the variables from file in the third argument
# If variables contains '.' then it's changed for underscore '_'
if [ -f "$VARIABLESFILE" ]; then
  VARS=`cat "$VARIABLESFILE" | sed 's/\./_/g'`
  eval "$VARS"
fi

# Parsing variables defined as script options
# variable means '-Dname=value'
parseVariables "$@"
shift $PARSED_VARIABLES

# Injecting data from augeas rule file to TEMPLATE var
# simple way: TEMPLATE=`eval "echo \"$(cat \"$AUGEASFILE\")\""`
TEMPLATE=
evalAugeas "$AUGEASFILE"
[ "$DEBUG" = true ] || [ "$debug" = true ] && echo "$TEMPLATE"


# -- And now let's rock'n'roll with Augeas itself --
augtool -Aeb -t "Xml.lns incl $XMLFILE" <<EOF
defvar file "/files${XMLFILE}"
$TEMPLATE
save
print /augeas//error
EOF


# Cleaning the output XML file by tidyp if available
tidyp -v > /dev/null 2>&1
if [ $? -eq 0 ]; then
  for I in $XMLFILE; do
    tidyp -xml -i -q < "$I" > "$I".tmp
    mv "$I".tmp "$I"
  done
fi

